### ISSUE TITLE
Grammatical mistake in readme

### ISSUE THREAD

**Issue by parammittal16** [CircleCI-Public/orb-starter-kit#23]
### What happened

Grammatical mistake in readme

### Expected behavior

The grammatical mistake should be removed from readme

**Comment by parammittal16** [comment]
Fixed some grammatical issues in Readme file. I want to correct them and work on this issue as of orbtoberfest. Can the required labels be added here @glenjarvis plz review

**Comment by glenjarvis** [comment]
@parammittal16 These changes (In https://github.com/CircleCI-Public/orb-starter-kit/pull/24) look good to me.
