### ISSUE TITLE
Migrate existing orbs to use `orb-starter-kit`

### ISSUE THREAD

**Issue by tangrufus** [CircleCI-Public/orb-starter-kit#42]
Tried to an existing orbs to use `orb-starter-kit`.
`./orb-init.sh` fails because of orb name already exist.

Use case: Separate [monorepo](https://github.com/CircleCI-Public/circleci-orbs) into their own respective repositories.

Foreseeable difficulties:
- handle exist orb names
- make the new git repo aware of old releases

Questions: 
Any workround to migrate existing orbs to use `orb-starter-kit`?

If using new orb name is the recommanded way, any way to rename an existing circleci orb?

**Comment by gmemstr** [comment]
The orb starter kit is being replaced with https://github.com/CircleCI-Public/Orb-Project-Template and the `orb init` command in the CircleCI CLI - docs are coming soon. It should be easier to examine the project template and bring in pieces from the configuration present there.
